[project]
dependencies = [
  "mediapipe>=0.10.35",
  "numpy>=2.5.1",
  "opencv-python>=5.0.0.93",
  "ultralytics>=8.4.121",
]
description = "Add your description here"
name = "gesture-detection"
readme = "README.md"
requires-python = ">=3.9"
version = "0.1.0"

[project.scripts]
gesture-detection = "gesture_detection.app:main"
